### ISSUE TITLE
INIT.pdb and Mass.dat file formats

### ISSUE THREAD

**Issue by rowanwalker96** [balaka92/TIS-DNA-Ex-Ion#1]
Hi there,

I would like to run simulations of single stranded dT30 and dA30 using the TIS-DNA model at 0mM salt.

It is unclear to me what the format of INIT.pdb should be. Is this just an all atom pdb file of the nucleic acid or a coarse grained pdb file? If it is coarse grained how do I go about generating this file? Also is Mass.dat just a file containing a column of the atomic masses?

Are there any other files I would need to run the simulation?

Thanks for your help,
Rowan

**Comment by balaka92** [comment]
Hi Rowan,
To run TIS-DNA simulations you will need to have some salt concentration
 to ensure charge neutrality of the system.

I apologize as the current repo is incomplete. I had taken down the
majority of the scripts to rewrite them in a more user-friendly manner. In
the modified version, you need to provide sequence information, whether you
are interested in ssDNA or dsDNA and a salt concentration to run the code.
I will upload it by this week.

Please let me know if you face any difficulties while running the code.

best,

Balaka

**Comment by balaka92** [comment]
please look here (https://github.com/balaka92/TIS-DNA-Ex-Ion/releases/tag/v0.0.0-TIS-ION) for the updated version.
